"""modify table games

Revision ID: 11247e4b6310
Revises: d074acf4edb3
Create Date: 2025-09-19 16:15:10.702223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '11247e4b6310'
down_revision: Union[str, Sequence[str], None] = 'd074acf4edb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('game', sa.String(length=60), nullable=True))
    op.add_column('games', sa.Column('season', sa.String(length=4), nullable=True))
    op.drop_column('games', 'active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('games', 'season')
    op.drop_column('games', 'game')
    # ### end Alembic commands ###
