"""add picks table

Revision ID: 9cd71cb54490
Revises: 11247e4b6310
Create Date: 2025-09-30 15:02:21.042492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cd71cb54490'
down_revision: Union[str, Sequence[str], None] = '11247e4b6310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('picks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.Column('gameID', sa.Integer(), nullable=True),
    sa.Column('userpick', sa.String(length=60), nullable=True),
    sa.Column('outcome', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('picks')
    # ### end Alembic commands ###
