"""adding games table

Revision ID: d074acf4edb3
Revises: 40420729a943
Create Date: 2025-09-19 11:25:15.602450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd074acf4edb3'
down_revision: Union[str, Sequence[str], None] = '40420729a943'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('team1', sa.String(length=30), nullable=True),
    sa.Column('team2', sa.String(length=30), nullable=True),
    sa.Column('finalscore1', sa.Integer(), nullable=True),
    sa.Column('finalscore2', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    # ### end Alembic commands ###
